services:
  api:
    container_name: api
    build:
      context: .
    restart: unless-stopped
    env_file:
      - .env
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/Caddydata:/data
      - ./caddy/caddy_config:/config
